"use client";

// import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import NavbarLogged from "@/components/NavbarLogged";
import { AppSidebar } from "@/components/app-sidebar";
import { useState } from "react";
import Particles from "@/components/ui/particles";

// export const metadata: Metadata = {
//   title: "DefiDetect",
//   description: "Generated by create next app",
// };

export default function Layout({ children }: { children: React.ReactNode }) {
  const [logged, setLogged] = useState(true);
  return (
    <html>
      <body>
        {logged ? (
          <SidebarProvider>
            <AppSidebar />
            {/* <main className="w-full flex">{children}</main> */}
            <div className="flex rounded-2xl overflow-hidden w-full h-[100dvh] mx-auto relative my-auto">
              <div className="h-full relative w-full overflow-auto">
                <div className="fixed w-full h-full z-[-1] flex items-center justify-center top-0 left-0 bg-[#020209]">
                  <div className="absolute aspect-square border w-[500px] z-[3] top-0 -translate-y-[70%] rounded-full bg-[#242528]"></div>
                  <div className="absolute aspect-square border w-[700px] z-[2] top-0 -translate-y-[70%] rounded-full bg-[#18181d]"></div>
                  <div className="absolute aspect-square w-[900px] z-[1] top-0 -translate-y-[70%] rounded-full bg-[#0b0a10]"></div>
                </div>
                {/* <div className="fixed inset-0 h-full w-full gridblock"></div> */}
                <NavbarLogged />
                {children}
              </div>
              {/* <div className="flex-none bg-card hidden xl:block relative w-[300px] border-l h-full">
                <nav className="sticky z-50 top-0 left-0 w-full border-b h-20 bg-[#08060e]/90 backdrop-blur flex items-center px-4">
                  <div className="w-full flex justify-end items-center gap-4">
                    <p className="text-sm rounded-full h-12 aspect-square bg-color1" />
                    <div>
                      <h1 className="text-lg">John Doe</h1>
                      <p className="text-xs text-[#6f6f72]">Admin</p>
                    </div>
                    <ChevronDown size={16} />
                  </div>
                </nav>
  
                <div className="p-4">
                  <div className="flex w-full items-end justify-between">
                    <p>Notifications</p>
                    <p className="text-xs text-color1">See all</p>
                  </div>
                </div>
              </div> */}
            </div>
          </SidebarProvider>
        ) : (
          <>
            <div className="min-h-screen w-full">
              <Particles
                className="absolute inset-0"
                quantity={200}
                ease={80}
                color={"#ffffff"}
                refresh
              />
            </div>
          </>
        )}
      </body>
    </html>
  );
}
